import {Dimensions, StyleSheet} from 'react-native';

export default StyleSheet.create({
    max: {
        height: '100%',
        width: '100%',
        position: 'absolute',
    },
    buttonHolder: {
        position: 'absolute',
        height: 40,
        alignSelf: 'center',
        top: '50%',
        flexDirection: 'row',
    },
    button: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        backgroundColor: '#0093E9',
        borderRadius: 25,
        zIndex: 1,
    },
    buttonText: {
        color: '#fff',
    },
    localview: {
        position: 'absolute',
        bottom: 8,
        right: 8,
        width: 124,
        height: 124,
        marginHorizontal: 2.5,
        overflow: 'hidden',
        borderRadius: 16,
    },
    remoteContainer: {
        width: '100%',
        height: 124,
        position: 'absolute',
        top: 8,
        marginHorizontal: 8,
    },
    remote: {
        width: 124,
        height: 124,
        marginHorizontal: 2.5,
        overflow: 'hidden',
        borderRadius: 16,
    },
    noUserText: {
        paddingHorizontal: 10,
        paddingVertical: 5,
        color: '#0093E9',
    },
    videoControlsOverlay: {
        overflow: 'hidden',
        alignItems: 'center',
        position: 'absolute',
        top: 0,
        bottom: 0,
        right: 0,
        left: 0,
        justifyContent: 'flex-end',
    },
    rightButton: {
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 1,
        paddingHorizontal: 6,
        width: 32,
        borderWidth: 0,
    },
    leftButton: {
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 1,
        paddingHorizontal: 6,
        width: 32,
        borderWidth: 0,
    },
    btnGroup: {
        color: 'white',
        height: 32,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        borderColor: 'rgba(255, 255, 255, 0.1)',
        borderWidth: 1,
        borderStyle: 'solid',
        marginBottom: 8,
        borderRadius: 8,
    },
    btnSeperator: {
        borderLeftWidth: 2,
        borderStyle: 'solid',
        borderColor: 'rgba(255,255,255,0.12)',
        height: 18,
        marginVertical: 'auto',
        marginHorizontal: 0,
    },
});
