import {Dimensions, StyleSheet} from 'react-native';

export default StyleSheet.create({
    max: {
        height: '100%',
        width: '100%',
        position: 'absolute',
    },
    buttonHolder: {
        position: 'absolute',
        height: 40,
        alignSelf: 'center',
        top: '50%',
        flexDirection: 'row',
    },
    button: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        backgroundColor: '#0093E9',
        borderRadius: 25,
        zIndex: 1,
    },
    buttonText: {
        color: '#fff',
    },
    localview: {
        position: 'absolute',
        bottom: 8,
        right: 8,
        width: 124,
        height: 124,
        marginHorizontal: 2.5,
        overflow: 'hidden',
        borderRadius: 16,
    },
    remoteContainer: {
        width: '100%',
        height: 124,
        position: 'absolute',
        top: 8,
        marginHorizontal: 8,
    },
    remote: {
        width: 124,
        height: 124,
        marginHorizontal: 2.5,
        overflow: 'hidden',
        borderRadius: 16,
    },
    noUserText: {
        paddingHorizontal: 10,
        paddingVertical: 5,
        color: '#0093E9',
    },
    videoControlsOverlay: {
        overflow: 'hidden',
        alignItems: 'center',
        borderColor: 'white',
        position: 'absolute',
        top: 0,
        bottom: 0,
        right: 0,
        left: 0,
    },
    rightButton: {
        borderWidth: 1,
        borderTopRightRadius: 4,
        borderBottomRightRadius: 4,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 2,
    },
    leftButton: {
        borderWidth: 1,
        borderTopLeftRadius: 4,
        borderBottomLeftRadius: 4,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 2,
    },
});
